from hdbcli import dbapi
import random
import string

# Connect to SAP HANA Cloud
cc = dbapi.connect(
    address="f2276c2f-a411-47a5-a9aa-1a60ff2469de.hana.trial-us10.hanacloud.ondemand.com",
    port=443,
    user="DBADMIN",
    password="Password12345"
)

def generate_group_code(length=12):
    chars = string.ascii_letters + string.digits
    return ''.join(random.choices(chars, k=length))

def create_groups_table():
    cur = cc.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM "SYS"."TABLES"
        WHERE "TABLE_NAME" = 'GROUPS' AND "SCHEMA_NAME" = CURRENT_SCHEMA
    """)
    exists = cur.fetchone()[0]

    if exists == 0:
        cur.execute("""
            CREATE COLUMN TABLE "GROUPS" (
                group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                group_name NVARCHAR(255),
                group_members NCLOB,
                group_balance DOUBLE,
                monthly_deposit_amount DOUBLE,
                grace_period INTEGER,
                min_credit_score INTEGER,
                monthly_deposit_date DATE,
                group_goal DOUBLE,
                group_code NVARCHAR(32)
            )
        """)
        print("✅ GROUPS table created.")
    else:
        print("ℹ️ GROUPS table already exists.")

    cc.commit()
    cur.close()

def get_valid_members(emails):
    cur = cc.cursor()
    valid = []

    for email in emails:
        cur.execute('SELECT 1 FROM USER_PROFILES WHERE email = ?', (email,))
        if cur.fetchone():
            valid.append(email)
        else:
            print(f"⚠️ Skipping invalid email: {email}")

    cur.close()
    return valid

def create_group(group_name, group_members, group_balance,
                 monthly_deposit_amount, grace_period,
                 min_credit_score, monthly_deposit_date, group_goal):

    valid_members = get_valid_members(group_members)

    if not valid_members:
        print("❌ No valid members found. Group not created.")
        return

    group_code = generate_group_code()
    cur = cc.cursor()

    cur.execute("""
        INSERT INTO "GROUPS" (
            "group_name",
            "group_members",
            "group_balance",
            "monthly_deposit_amount",
            "grace_period",
            "min_credit_score",
            "monthly_deposit_date",
            "group_goal",
            "group_code"
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        group_name,
        ','.join(valid_members),
        group_balance,
        monthly_deposit_amount,
        grace_period,
        min_credit_score,
        monthly_deposit_date,
        group_goal,
        group_code
    ))


    cc.commit()
    cur.close()
    print(f"✅ Group '{group_name}' created with members: {valid_members}")
    print(f"🆔 Group Code: {group_code}")

if __name__ == "__main__":
    # Uncomment this once to create the table, then keep it commented
    # create_groups_table()

    create_group(
        group_name="Test Group",
        group_members=[
            'mustafa.bookwala@sap.com',
            'lucas.loepke@sap.com',
            'nyle.coleman@sap.com',
            'invalid@sap.com'
        ],
        group_balance=0.00,
        monthly_deposit_amount=10.0,
        grace_period=10,
        min_credit_score=400,
        monthly_deposit_date="2025-08-10",
        group_goal=20000.0
    )
